---
apiVersion: v1
kind: Secret
metadata:
  name: oidc-cli
  labels:
    app.kubernetes.io/part-of: tpa
type: Opaque
stringData:
  client-id: walker
  client-secret: walker-secret-for-demo
---
apiVersion: rhtpa.io/v1
kind: TrustedProfileAnalyzer
metadata:
  name: trustify
  labels:
    app.kubernetes.io/part-of: tpa
spec:
  appDomain: .APPS_DOMAIN
  oidc:
    issuerUrl: KEYCLOAK_ISSUER_PLACEHOLDER
    clients:
      frontend:
        clientId: frontend
      cli:
        clientId: walker
        clientSecret:
          secret: oidc-cli
          key: client-secret
  database:
    host: postgresql.NAMESPACE.svc.cluster.local
    port: "5432"
    name: trustify
    username: trustify
    password: trustify-demo-password
  storage:
    type: s3
    accessKey: minioadmin
    secretKey: minioadmin-demo-password
    bucket: trustify
    region: http://minio.NAMESPACE.svc.cluster.local:9000
  createDatabase:
    enabled: true
    image: {}
    adminUsername: postgres
    adminPassword: postgres-admin-password
  migrateDatabase:
    enabled: true
    image: {}
    adminUsername: postgres
    adminPassword: postgres-admin-password
  modules:
    server:
      enabled: true
      image: {}
      infrastructure: {}
      ingress: {}
      metrics: {}
      replicas: 1
      resources:
        requests:
          cpu: 500m
          memory: 2Gi
      rust: {}
      tracing: {}
    importer:
      enabled: true
      image: {}
      infrastructure: {}
      metrics: {}
      replicas: 1
      concurrency: 1
      resources:
        requests:
          cpu: 500m
          memory: 2Gi
      rust: {}
      tracing: {}
      workingDirectory:
        size: 10Gi
    createImporters:
      enabled: true
      image: {}
      importers:
        redhat-csaf-vex:
          period: 30m
          source: https://access.redhat.com/security/data/csaf/v2/provider-metadata.json
          v3Signatures: true
        redhat-csaf:
          period: 30m
          source: https://access.redhat.com/security/data/csaf/v2/provider-metadata.json
          v3Signatures: true
          onlyPrefixes:
            - cve-
  openshift:
    useServiceCa: true
  ingress: {}
  infrastructure:
    port: 9010
  metrics:
    enabled: false
  tracing:
    enabled: false
  tls: {}
  rust: {}
  collector: {}
  image: {}
