server:
  port: 8080

app:
  profile: "@app.profile@"
  version: "@project.version@"
  dep-versions:
    woodstox-core: "@woodstox.version@"
    json-path: "@jsonpath.version@"
    json: "@orgjson.version@"
    spring-core: "@spring-core.version@"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
