apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: catalog-remediated-
  labels:
    app.kubernetes.io/part-of: lightwell-demo
    demo.lightwell/variant: remediated
spec:
  pipelineRef:
    name: secure-catalog-pipeline
  params:
    - name: GIT_REPO
      value: "https://github.com/andykrohg/lightwell-ocp-demo.git"
    - name: GIT_REVISION
      value: main
    - name: MAVEN_PROFILE
      value: remediated
    - name: IMAGE_NAME
      value: "__REGISTRY_HOST__/catalog-app"
    - name: IMAGE_TAG
      value: remediated-latest
    - name: NAMESPACE
      value: __DEMO_NAMESPACE__
    - name: TPA_URL
      value: "__TPA_URL__"
    - name: TPA_OIDC_ISSUER_URL
      value: "__TPA_OIDC_ISSUER_URL__"
    - name: TPA_CLIENT_ID
      value: walker
    - name: TPA_CLIENT_SECRET
      value: "__TPA_CLIENT_SECRET__"
    - name: ROX_CENTRAL_ENDPOINT
      value: "__ROX_CENTRAL_ENDPOINT__"
    - name: ROX_API_TOKEN
      value: "__ROX_API_TOKEN__"
    - name: SOFT_FAIL
      value: "false"
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: pipeline-workspace-pvc
    - name: maven-settings
      emptyDir: {}
