apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: remediated-

resources:
  - ../../base/catalog-app

commonLabels:
  app.demo/variant: remediated

images:
  - name: IMAGE_PLACEHOLDER
    newName: __REGISTRY_HOST__/catalog-app
    newTag: remediated-latest

configMapGenerator:
  - name: catalog-app-config
    literals:
      - SPRING_PROFILES_ACTIVE=remediated
