FROM registry.access.redhat.com/ubi9/openjdk-17-runtime:latest

COPY target/*.jar /deployments/app.jar
COPY target/bom.json /deployments/bom.json

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/deployments/app.jar"]
